using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SceneStateModel
{
    //Holds annotations and their locations on the model
    private Dictionary<Vector3, string> _modelAnnotations = new Dictionary<Vector3, string>();
    
    
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SceneStateModel : RealtimeModel {
    public SceneStateModel() : base(null) {
    }
    
    protected override int WriteLength(StreamContext context) {
        return 0;
    }
    protected override void Write(WriteStream stream, StreamContext context) {
    }
    protected override void Read(ReadStream stream, StreamContext context) {
    }
    private void UpdateBackingFields() {
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
