using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class SceneStateModel
{
    //This gives us the opportunity to let other clients add 3D objects to our scene, we will need a way to get the 3d Model that the ObjectViewModel holds (perhaps a hosted URL?): Unity Web Request
    [RealtimeProperty(1,true,true)]
    private RealtimeSet<ObjectViewModel> _objectViews;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class SceneStateModel : RealtimeModel {
    public SceneStateModel() : base(null) {
    }
    
    protected override int WriteLength(StreamContext context) {
        return 0;
    }
    protected override void Write(WriteStream stream, StreamContext context) {
    }
    protected override void Read(ReadStream stream, StreamContext context) {
    }
    private void UpdateBackingFields() {
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
