//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/Input/HostControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @HostControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @HostControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""HostControls"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""58608a18-561e-4068-a560-359d2f33a04f"",
            ""actions"": [
                {
                    ""name"": ""Select Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ea6bc4f0-9d6e-48ed-bc2b-a1a7bd17b2f0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select UI"",
                    ""type"": ""Button"",
                    ""id"": ""a2b8de67-fe98-47c2-b9f5-555eec21ef73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e07fc459-5587-48b9-8f1d-95058d0b0775"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""faf25f89-fc41-45d3-9450-c42ca037988a"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32f7c074-3c92-45c9-8d2d-e7eb9e7a220f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select UI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7709227b-97eb-4896-a9ba-740371466696"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select UI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_SelectPosition = m_Default.FindAction("Select Position", throwIfNotFound: true);
        m_Default_SelectUI = m_Default.FindAction("Select UI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private IDefaultActions m_DefaultActionsCallbackInterface;
    private readonly InputAction m_Default_SelectPosition;
    private readonly InputAction m_Default_SelectUI;
    public struct DefaultActions
    {
        private @HostControls m_Wrapper;
        public DefaultActions(@HostControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectPosition => m_Wrapper.m_Default_SelectPosition;
        public InputAction @SelectUI => m_Wrapper.m_Default_SelectUI;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void SetCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterface != null)
            {
                @SelectPosition.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSelectPosition;
                @SelectPosition.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSelectPosition;
                @SelectPosition.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSelectPosition;
                @SelectUI.started -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSelectUI;
                @SelectUI.performed -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSelectUI;
                @SelectUI.canceled -= m_Wrapper.m_DefaultActionsCallbackInterface.OnSelectUI;
            }
            m_Wrapper.m_DefaultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectPosition.started += instance.OnSelectPosition;
                @SelectPosition.performed += instance.OnSelectPosition;
                @SelectPosition.canceled += instance.OnSelectPosition;
                @SelectUI.started += instance.OnSelectUI;
                @SelectUI.performed += instance.OnSelectUI;
                @SelectUI.canceled += instance.OnSelectUI;
            }
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnSelectPosition(InputAction.CallbackContext context);
        void OnSelectUI(InputAction.CallbackContext context);
    }
}
